"""init schema

Revision ID: 5ad279ea8cae
Revises: 001_initial
Create Date: 2026-02-27 00:34:18.811984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad279ea8cae'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite names UNIQUE constraints differently than PostgreSQL (e.g. sqlite_autoindex_*),
    # so batch drop of products_slug_key / users_email_key fails on fresh SQLite.
    # On SQLite, 001_initial already enforces slug/email uniqueness; nothing to drop.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_slug_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('products_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
